name: ufraw-batch
version: '0.20'
summary: Unidentified Flying Raw converter for digital camera images
description: |
  This is the batch image processor of UFRaw.

grade: stable
confinement: strict

apps:
  ufraw-batch:
    command: ufraw-batch
    plugs: [home, removable-media]

parts:
  my-part:
    plugin: nil
    stage-packages: [ufraw-batch]
